name: darttransfer
description: A simple Dart Wetransfer Client
version: 1.0.0
homepage: https://github.com/AraxTheCoder/darttransfer

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  http: ^0.13.5
  archive: ^3.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
